### ISSUE TITLE
Design the uninhabitated world

### ISSUE THREAD

**Issue by n0la** [ehrpg/qstar-playtest#1]
We have agreed to place the players on an uninhabited world. To move them there the players will move with a science vessel to the planet, which then is nearly destroyed by FTL sabotage. The players, along with their friends and colleagues, then descent onto the planet with a shuttle.

Core stats: 0.9g
Atmosphere: 8% oxygen, 0.93% argon, 0.07% carbon dioxide, 91% nitrogen

**Comment by johannes-z** [comment]
## Environmental Hazards:

* Violent Thunderstorms: For very long periods thunderstorms rage across the landscape. This hinders communication over longer distances (radios), but also makes long range communications via a comms array impossible.

**Comment by n0la** [comment]
Done.
