### ISSUE TITLE
Design flora/fauna

### ISSUE THREAD

**Issue by n0la** [ehrpg/qstar-playtest#2]
For the planet that is being designed in #1 we also need a few creatures and plants. Perhaps a few plant eaters, plants (both poisonous and edible) but also predators that become a problem for the settlers.

**Comment by johannes-z** [comment]
## Fauna

* Raptors: Named after the well-known earthen raptor, these creatures are lizard-like predators that hunt in packs. They show strength in numbers, scavenging for meat of living and dead creatures, although they are easily scared and routed.

**Comment by n0la** [comment]
We decided once that we don't want anything living on the planet's surface. And since fauna is not possible without flora, the surface will remain lifeless.
